version: "3.9"

services:
  #front-end:
  #  build:
  #    context: ./../Streetcode/Streetcode.Client
  #    dockerfile: Dockerfile
  #  init: true
  #  restart: always
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    back-end:
  # condition: service_healthy
  
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5000" # ;https://*:5001
    volumes:
      - "./healthchecks:/healthchecks"
    deploy:
      labels:
        atom: "Streetcode"
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      CONNECTION_STRING: "Server=localhost;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};MultipleActiveResultSets=true"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "$$SA_PASSWORD", "-Q", "select 1", " -b", "-o /dev/null"]
      interval: 3s
      retries: 20
    #secrets:
    #  - db-password
    volumes:
      - db-data:/var/lib/mssql/data
      - "./healthchecks:/healthchecks"
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${MS_SQL_DB_PORT}:1433/tcp"
    deploy:
      labels:       
        atom: "Streetcode"
      
  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"   
    healthcheck:
      test: /.healthchecks/redis.sh
      interval: "5s"
    deploy:
      labels:
        atom: "Streetcode"
      
  # this service runs once to seed the database
  # it won't run unless you specify the "seed" profile
  # docker compose --profile seed up -d
  #seed:
  #  build:
  #    context: ./Streetcode.Seed
  #    dockerfile: Dockerfile
  #  profiles: ["seed"]
  #  depends_on:
  #    back-end:
  #      condition: service_healthy
  # restart: "no"
  #  deploy:
  #    labels:
  #      atom: "Streetcode"
      
volumes:
  db-data: {}
  
#secrets:
#  db-password:
#    file: ./???